version: '2.1'
services:
  postgres:
    restart: always
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./postgres-data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    labels:
      kompose.service.type: NodePort
      kompose.service.nodeport.port: "30000"
  web:
    restart: always
    build: .
    ports:
      - 8080:8080
    volumes:
      - .:/web
    labels:
      kompose.service.type: NodePort
      kompose.service.nodeport.port: "30002"

