apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Windows\system32\kompose.exe convert
    kompose.service.nodeport.port: "30002"
    kompose.service.type: NodePort
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: web
  name: web
spec:
  ports:
    - name: "8080"
      nodePort: 30002
      port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: web
  type: NodePort
status:
  loadBalancer: {}
